# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a15tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Vivado/ROT_7SEG/ROT_7SEG.cache/wt [current_project]
set_property parent.project_path Z:/Vivado/ROT_7SEG/ROT_7SEG.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/Vivado/ROT_7SEG/ROT_7SEG.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib Z:/Vivado/ROT_7SEG/ROT_7SEG.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/Vivado/ROT_7SEG/ROT_7SEG.xdc
set_property used_in_implementation false [get_files Z:/Vivado/ROT_7SEG/ROT_7SEG.xdc]


synth_design -top ROT_7SEG -part xc7a15tcpg236-1


write_checkpoint -force -noxdef ROT_7SEG.dcp

catch { report_utilization -file ROT_7SEG_utilization_synth.rpt -pb ROT_7SEG_utilization_synth.pb }
