# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/github/Vivado/CNT60_ALL/CNT60_ALL.cache/wt [current_project]
set_property parent.project_path Z:/github/Vivado/CNT60_ALL/CNT60_ALL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  Z:/github/Vivado/CNT60_ALL/ENABLE_GEN.v
  Z:/github/Vivado/CNT60_ALL/DECODER7.v
  Z:/github/Vivado/CNT60_ALL/dcount.v
  Z:/github/Vivado/CNT60_ALL/CNT60.v
  Z:/github/Vivado/CNT60_ALL/CNT_ALL.v
}
read_xdc Z:/github/Vivado/CNT60_ALL/CNT60_ALL.xdc
set_property used_in_implementation false [get_files Z:/github/Vivado/CNT60_ALL/CNT60_ALL.xdc]

synth_design -top CNT60_ALL -part xc7a35tcpg236-1
write_checkpoint -noxdef CNT60_ALL.dcp
catch { report_utilization -file CNT60_ALL_utilization_synth.rpt -pb CNT60_ALL_utilization_synth.pb }
