# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a15tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/github/Vivado/UPDOWN_7SEG/UPDOWN_7SEG.cache/wt [current_project]
set_property parent.project_path Z:/github/Vivado/UPDOWN_7SEG/UPDOWN_7SEG.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  Z:/github/Vivado/UPDOWN10_2/UPDOWN10_2.v
  Z:/github/Vivado/DECODER7/DECODER7.v
  Z:/github/Vivado/UPDOWN_7SEG/UPDOWN_7SEG.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top UPDOWN_7SEG -part xc7a15tcpg236-1


write_checkpoint -force -noxdef UPDOWN_7SEG.dcp

catch { report_utilization -file UPDOWN_7SEG_utilization_synth.rpt -pb UPDOWN_7SEG_utilization_synth.pb }
